project:
  type: website
  output-dir: docs

website:
  title: "CSAMA 2025 - Materials"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Programme"
        href: programme.qmd
      - text: "Lectures"
        menu:
          - href: lectures/day1.qmd
            text: "Day 1"
          - href: lectures/day2.qmd
            text: "Day 2"
          - href: lectures/day3.qmd
            text: "Day 3"
          - href: lectures/day4.qmd
            text: "Day 4"
          - href: lectures/day5.qmd
            text: "Day 5"
      - text: "Resources"
        href: resources.qmd
  page-footer:
    center: |
      [GitHub Repo](https://github.com/tuo-username/tuo-repo) • Built with [Quarto](https://quarto.org)

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
