project:
  type: website
  output-dir: docs

website:
  title: "CSAMA 2025 - Materials"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        menu:
          - href: lectures/01_intro.qmd
            text: "Introduction"
          - href: lectures/02_singlecell.qmd
            text: "Single-cell Analysis"
          - href: lectures/03_images.qmd
            text: "Image Analysis"
      - text: "Resources"
        href: resources.qmd
  page-footer:
    center: |
      [GitHub Repo](https://github.com/tuo-username/tuo-repo) • Built with [Quarto](https://quarto.org)

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
