---
title: "CSAMA 2025 - Workshop Materials"
format: html
---

# Welcome

This website contains materials for the **CSAMA 2025** workshop, covering key concepts in:

- Statistical analysis of high-throughput data
- Single-cell RNA sequencing
- Histopathological image analysis

You can find lecture notes, slides, code, and datasets in the corresponding sections.


To run the code locally, make sure you have the required R packages installed. See the **Resources** page for more info.

```{.callout-note}
To run the code locally, make sure you have the required R packages installed. See the **Resources** page for more info.
```

# Overview

The one-week intensive summer school Biological Data Science teaches advanced computational analyses of modern molecular data types in biology and biomedicine, including single cell and spatial omics. It comprises lectures covering underlying theory and concepts, practical hands-on exercises, and informal discussion sessions. Lecture topics include modern biotechnologies for quantitative measurements, statistical analysis, visualisation, and computational tools. Hands-on exercises are looking at state-of-the-art datasets, using the R / Bioconductor environment. At the end of the course, you should be better able to design, implement and interpret analyses on your own (multi-)omic, single and/or spatial data, adapt and combine different tools, and make informed and scientifically sound choices about analysis strategies.

# Faculty and Teaching Assistants

Anne-Laure Boulesteix, Ludwig Maximilians Universitat Munchen
Vince Carey, Harvard Medical School
Maria Doyle, University of Limerick
Laurent Gatto, UCLouvain
Robert Gentleman, Harvard Medical School
Wolfgang Huber, European Molecular Biology Laboratory
Philippine Louail, Eurac Research
Michael Love, University of North Carolina at Chapel Hill
Davide Risso, University of Padova
Charlotte Soneson, Friedrich Miescher Institute for Biomedical Research
Ilaria Billato, University of Padova
